CBOW:
  CBOW_EMBED_DIMENSIONS: 100
  CBOW_WINDOW: 4
  CBOW_MAX_LENGTH: 50
  CBOW_BATCH_SIZE: 1024
  CBOW_NUM_EPOCHS: 10
  CBOW_LEARNING_RATE: 5e-5
SKIP_GRAM:
  SKIP_EMBED_DIMENSIONS: 100
  SKIP_WINDOW: 4
  SKIP_MAX_LENGTH: 50
  SKIP_BATCH_SIZE: 1024
  SKIP_NUM_EPOCHS: 10
  SKIP_LEARNING_RATE: 5e-5